## Exploración inicial de datos

Exploración de los subconjuntos de datos seleccionados del dataset LITNET-2020. El objetivo es comprender la estructura de cada archivo, identificar la cantidad de registros, variables disponibles, presencia de valores nulos y la distribución de las etiquetas de clasificación.

Flujos de ataques: Blaster Worm, Reaper Worm, Red Worm, HTTP flood, ICMP flood y UDP flood.

In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [7]:
DATA_PATH = "../data/raw/"
files = [
    "BLASTER_WORM_v2.csv",
    "HTTP_FLOOD_v2.csv",
    "ICMP_FLOOD_v2.csv",
    "REAPER_WORM_v2.csv",
    "RED_WORM_v2.csv",
    "UDP_FLOOD_v2.csv"
]
files_paths = [os.path.join(DATA_PATH, f) for f in files]
files_paths

['../data/raw/BLASTER_WORM_v2.csv',
 '../data/raw/HTTP_FLOOD_v2.csv',
 '../data/raw/ICMP_FLOOD_v2.csv',
 '../data/raw/REAPER_WORM_v2.csv',
 '../data/raw/RED_WORM_v2.csv',
 '../data/raw/UDP_FLOOD_v2.csv']

In [8]:
column_names = [f"feature_{i+1}" for i in range(83)] + ["attack_t", "attack_a"]

In [9]:
def explorar(path, nrows=100000):
    print("="*80)
    print(f"Archivo: {os.path.basename(path)}")
    
    df = pd.read_csv(path, header=None, names=column_names, nrows=nrows)
    
    print("\nShape (muestra):", df.shape)
    
    print("\nPrimeras filas:")
    display(df.head())
    
    print("\nTipos de datos:")
    print(df.dtypes.value_counts())
    
    print("\nValores nulos (%):")
    nulls = df.isnull().mean().sort_values(ascending=False)
    print(nulls.head(10))
    
    print("\nDistribución attack_a:")
    print(df["attack_a"].value_counts(dropna=False))
    print(df["attack_a"].value_counts(normalize=True, dropna=False))
    
    print("\nDistribución attack_t:")
    print(df["attack_t"].value_counts(dropna=False))
    
    print("\nMemoria estimada muestra (MB):")
    print(round(df.memory_usage(deep=True).sum() / 1024**2, 2))
    
    return df

In [10]:
for path in files_paths:
    _ = explorar(path)

================================================================================
Archivo: BLASTER_WORM_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2020,1,25,3,44,57,2020,1,25,3,44,57,0.28,193.219.74.172,83.169.5.121,59758,3306,TCP,.,A,P,.,.,F,0,8,10,1080,0,0,762,556,2847,8972,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2020,1,25,3,44,52,2020,1,25,3,44,57,4.73,184.73.156.247,193.219.75.85,443,58895,TCP,.,A,.,.,.,F,0,0,10,7300,0,0,707,588,14618,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2020,1,25,3,44,57,2020,1,25,3,44,57,0.00,83.171.40.3,80.82.77.132,6666,56667,TCP,.,A,.,R,.,.,0,0,5,200,0,0,922,556,2847,202425,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2020,1,25,3,44,38,2020,1,25,3,44,57,19.29,95.108.213.17,158.129.192.240,62443,80,TCP,.,A,.,.,S,F,0,164,20,1080,0,0,556,558,13238,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2020,1,25,3,44,55,2020,1,25,3,44,57,1.82,124.115.207.226,158.129.192.178,56637,33896,TCP,.,A,P,R,.,.,0,0,10,825,0,0,707,558,4134,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    99919
1       81
Name: count, dtype: int64
attack_a
0    0.99919
1    0.00081
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none         99919
tcp_w32_w       81
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.5
================================================================================
Archivo: HTTP_FLOOD_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2020,1,16,9,29,46,2020,1,16,9,29,57,10.41,83.171.0.105,185.33.223.210,51082,443,TCP,.,A,.,.,S,F,0,0,20,8160,0,0,1029,556,2847,29990,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2020,1,16,9,29,57,2020,1,16,9,29,57,0.00,193.219.81.24,95.100.138.18,64071,443,TCP,.,A,.,R,.,.,0,0,5,200,0,0,558,707,2847,16625,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2020,1,16,9,29,49,2020,1,16,9,29,57,7.54,83.171.17.134,93.184.221.240,57252,80,TCP,.,A,P,.,S,F,0,0,95,12575,0,0,558,556,2847,15133,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2020,1,16,9,29,9,2020,1,16,9,29,57,47.56,83.171.17.121,3.121.254.42,54317,443,TCP,.,A,P,.,.,F,0,0,65,10205,0,0,616,556,2847,16509,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2020,1,16,9,29,17,2020,1,16,9,29,57,40.13,193.219.183.180,104.102.20.152,53275,443,TCP,.,A,P,.,.,F,0,0,50,4215,0,0,699,707,2847,16625,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    99394
1      606
Name: count, dtype: int64
attack_a
0    0.99394
1    0.00606
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none      99394
http_f      606
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.52
================================================================================
Archivo: ICMP_FLOOD_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2020,1,31,15,34,58,2020,1,31,15,34,58,0.000,74.82.47.39,193.219.37.61,43619,3389,TCP,.,.,.,.,.,.,0,0,1,46,0,0,170,50,6939,0,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,2,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2020,1,31,15,34,58,2020,1,31,15,34,58,0.064,193.219.137.93,88.119.142.219,443,62470,TCP,.,.,.,.,.,.,0,0,3,759,0,0,3,190,5479,8764,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,2,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2020,1,31,15,34,58,2020,1,31,15,34,58,0.000,83.171.35.62,83.171.33.3,58110,53,UDP,.,.,.,.,.,.,0,0,1,76,0,0,213,50,0,0,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,2,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2020,1,31,15,34,58,2020,1,31,15,34,59,0.192,193.219.185.52,192.48.236.9,47904,443,TCP,.,.,.,.,.,.,0,0,2,104,0,0,213,50,0,0,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,2,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2020,1,31,15,34,58,2020,1,31,15,34,59,0.896,5.20.223.18,193.219.162.82,80,57497,TCP,.,.,.,.,.,.,0,0,11,15972,0,0,107,50,21412,0,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,2,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    98454
1     1546
Name: count, dtype: int64
attack_a
0    0.98454
1    0.01546
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none        98454
icmp_smf     1287
icmp_f        259
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.54
================================================================================
Archivo: REAPER_WORM_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2019,10,2,7,48,54,2019,10,2,7,49,54,60.04,83.171.0.44,8.248.115.254,51233,80,TCP,.,A,P,.,.,F,0,0,8,712,0,0,558,556,2847,3356,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2019,10,2,7,48,54,2019,10,2,7,48,54,0.04,172.217.22.78,83.171.7.11,80,59787,TCP,.,A,.,.,S,.,0,164,4,224,0,0,556,700,15169,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2019,10,2,7,48,54,2019,10,2,7,48,54,0.00,162.88.2.12,193.219.153.45,53,20199,UDP,.,.,.,.,.,.,0,128,2,234,0,0,556,558,33517,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2019,10,2,7,48,54,2019,10,2,7,48,54,0.00,216.58.207.66,83.171.17.89,443,49346,UDP,.,.,.,.,.,.,0,164,2,2756,0,0,556,616,15169,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2019,10,2,7,48,54,2019,10,2,7,48,54,0.00,45.136.109.196,158.129.124.207,50838,2523,TCP,.,.,.,.,S,.,0,0,2,80,0,0,707,0,49505,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    99972
1       28
Name: count, dtype: int64
attack_a
0    0.99972
1    0.00028
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none            99972
udp_reaper_w       28
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.55
================================================================================
Archivo: RED_WORM_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2020,1,30,20,31,8,2020,1,30,20,31,8,0.00,187.240.167.48,193.219.81.138,22,26639,TCP,.,A,.,.,S,.,0,64,5,220,0,0,707,558,27672,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2020,1,30,20,31,8,2020,1,30,20,31,8,0.00,178.10.243.216,193.219.81.138,5060,27720,TCP,.,A,.,.,S,.,0,164,5,220,0,0,556,558,3209,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2020,1,30,20,31,8,2020,1,30,20,32,3,55.28,121.83.158.54,193.219.81.138,0,769,ICMP,.,.,.,.,.,.,0,192,10,720,0,0,707,558,17511,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2020,1,30,20,31,8,2020,1,30,20,31,8,0.00,109.145.167.245,193.219.81.138,7547,48625,TCP,.,A,.,.,S,.,0,0,5,220,0,0,707,558,2856,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2020,1,30,20,31,8,2020,1,30,20,31,8,0.00,24.158.216.38,193.219.81.138,7547,4588,TCP,.,A,.,.,S,.,0,0,5,220,0,0,707,558,20115,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,1,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    77777
1    22223
Name: count, dtype: int64
attack_a
0    0.77777
1    0.22223
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none         77777
tcp_red_w    22223
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.37
================================================================================
Archivo: UDP_FLOOD_v2.csv

Shape (muestra): (100000, 85)

Primeras filas:

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,attack_t,attack_a
0,1,2019,3,6,21,13,59,2019,3,6,21,13,59,0.0,193.219.160.102,84.53.139.192,55399,53,UDP,.,.,.,.,.,.,0,0,2,208,0,0,761,556,2847,21342,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,6,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
1,2,2019,3,6,21,13,59,2019,3,6,21,13,59,0.0,8.8.8.8,158.129.18.13,53,54945,UDP,.,.,.,.,.,.,0,0,2,210,0,0,707,505,15169,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,6,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
2,3,2019,3,6,21,13,59,2019,3,6,21,13,59,0.0,92.123.220.54,193.219.160.102,53,50042,UDP,.,.,.,.,.,.,0,0,2,258,0,0,707,761,20940,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,6,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
3,4,2019,3,6,21,13,59,2019,3,6,21,13,59,0.0,193.219.166.202,83.171.22.2,2449,53,UDP,.,.,.,.,.,.,0,0,2,136,0,0,816,505,2847,2847,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,6,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0
4,5,2019,3,6,21,13,59,2019,3,6,21,13,59,0.0,193.219.80.2,81.88.63.39,19393,53,UDP,.,.,.,.,.,.,0,0,2,162,0,0,558,556,2847,39729,0,0,0,0,0.0.0.0,0.0.0.0,0,0,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,00:00:00:00:00:00,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0-0-0,0.0,0.0,0.0,0.0.0.0,0/0,6,1970-01-01 03:00:00.000,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,none,0

Tipos de datos:
object     48
int64      33
float64     4
Name: count, dtype: int64

Valores nulos (%):
feature_1     0.0
feature_55    0.0
feature_63    0.0
feature_62    0.0
feature_61    0.0
feature_60    0.0
feature_59    0.0
feature_58    0.0
feature_57    0.0
feature_56    0.0
dtype: float64

Distribución attack_a:
attack_a
0    85872
1    14128
Name: count, dtype: int64
attack_a
0    0.85872
1    0.14128
Name: proportion, dtype: float64

Distribución attack_t:
attack_t
none     85872
udp_f    14128
Name: count, dtype: int64

Memoria estimada muestra (MB):
319.35

In [ ]:
resumen = []
for path in files_paths:
    df = pd.read_csv(path, header=None, names=column_names, nrows=100000)
    resumen.append({
        "archivo": os.path.basename(path),
        "filas_muestra": df.shape[0],
        "columnas": df.shape[1],
        "nulos_%_max_muestra": df.isnull().mean().max(),
        "attack_a_0_muestra": (df["attack_a"] == 0).sum(),
        "attack_a_1_muestra": (df["attack_a"] == 1).sum(),
        "attack_ratio_muestra": df["attack_a"].mean(),
        "attack_t_valores_muestra": df["attack_t"].unique().tolist()
    })
resumen_df = pd.DataFrame(resumen)
resumen_df

,archivo,filas_muestra,columnas,nulos_%_max_muestra,attack_a_0_muestra,attack_a_1_muestra,attack_ratio_muestra,attack_t_valores_muestra
0,BLASTER_WORM_v2.csv,100000,85,0.0,99919,81,0.00081,"[none, tcp_w32_w]"
1,HTTP_FLOOD_v2.csv,100000,85,0.0,99394,606,0.00606,"[none, http_f]"
2,ICMP_FLOOD_v2.csv,100000,85,0.0,98454,1546,0.01546,"[none, icmp_smf, icmp_f]"
3,REAPER_WORM_v2.csv,100000,85,0.0,99972,28,0.00028,"[none, udp_reaper_w]"
4,RED_WORM_v2.csv,100000,85,0.0,77777,22223,0.22223,"[none, tcp_red_w]"
5,UDP_FLOOD_v2.csv,100000,85,0.0,85872,14128,0.14128,"[none, udp_f]"

Nulos en todo el cvs

In [12]:
def revisar_nulos_completo(path, chunksize=500000):
    total_filas = 0
    nulos = pd.Series(0, index=column_names, dtype="int64")
    for chunk in pd.read_csv(path, header=None, names=column_names, chunksize=chunksize):
        total_filas += len(chunk)
        nulos += chunk.isnull().sum()
    porcentaje_nulos = (nulos / total_filas) * 100
    return pd.DataFrame({
        "columna": column_names,
        "nulos": nulos.values,
        "porcentaje_nulos": porcentaje_nulos.values
    }).sort_values("porcentaje_nulos", ascending=False)

In [13]:
nulos_globales = {}
for path in files_paths:
    nombre = os.path.basename(path)
    print(f"Revisando nulos completos en: {nombre}")
    nulos_globales[nombre] = revisar_nulos_completo(path)
nulos_globales["UDP_FLOOD_v2.csv"].head(10)

Revisando nulos completos en: BLASTER_WORM_v2.csv
Revisando nulos completos en: HTTP_FLOOD_v2.csv
Revisando nulos completos en: ICMP_FLOOD_v2.csv
Revisando nulos completos en: REAPER_WORM_v2.csv
Revisando nulos completos en: RED_WORM_v2.csv
Revisando nulos completos en: UDP_FLOOD_v2.csv

       columna  nulos  porcentaje_nulos
0    feature_1      0               0.0
54  feature_55      0               0.0
62  feature_63      0               0.0
61  feature_62      0               0.0
60  feature_61      0               0.0
59  feature_60      0               0.0
58  feature_59      0               0.0
57  feature_58      0               0.0
56  feature_57      0               0.0
55  feature_56      0               0.0

In [15]:
resumen_nulos = []
for nombre, df_nulos in nulos_globales.items():
    total_nulos = df_nulos["nulos"].sum()
    columnas_con_nulos = (df_nulos["nulos"] > 0).sum()
    max_nulos_columna = df_nulos["nulos"].max()
    resumen_nulos.append({
        "dataset": nombre,
        "total_nulos": total_nulos,
        "columnas_con_nulos": columnas_con_nulos,
        "max_nulos_en_una_columna": max_nulos_columna
    })
resumen_nulos_df = pd.DataFrame(resumen_nulos)
display(resumen_nulos_df)

,dataset,total_nulos,columnas_con_nulos,max_nulos_en_una_columna
0,BLASTER_WORM_v2.csv,0,0,0
1,HTTP_FLOOD_v2.csv,0,0,0
2,ICMP_FLOOD_v2.csv,0,0,0
3,REAPER_WORM_v2.csv,0,0,0
4,RED_WORM_v2.csv,0,0,0
5,UDP_FLOOD_v2.csv,0,0,0

Etiquetas unicas

In [16]:
for path in files_paths:
    nombre = os.path.basename(path)
    df = pd.read_csv(
        path,
        header=None,
        names=column_names,
        usecols=["attack_t", "attack_a"],
        nrows=100000
    )
    print("="*60)
    print(nombre)
    print("\nattack_t únicos:")
    print(df["attack_t"].unique())
    print("\nattack_a únicos:")
    print(df["attack_a"].unique())

============================================================
BLASTER_WORM_v2.csv

attack_t únicos:
['none' 'tcp_w32_w']

attack_a únicos:
[0 1]
============================================================
HTTP_FLOOD_v2.csv

attack_t únicos:
['none' 'http_f']

attack_a únicos:
[0 1]
============================================================
ICMP_FLOOD_v2.csv

attack_t únicos:
['none' 'icmp_smf' 'icmp_f']

attack_a únicos:
[0 1]
============================================================
REAPER_WORM_v2.csv

attack_t únicos:
['none' 'udp_reaper_w']

attack_a únicos:
[0 1]
============================================================
RED_WORM_v2.csv

attack_t únicos:
['none' 'tcp_red_w']

attack_a únicos:
[0 1]
============================================================
UDP_FLOOD_v2.csv

attack_t únicos:
['none' 'udp_f']

attack_a únicos:
[0 1]

- Todos los subconjuntos contienen 85 atributos.
- No se detectaron valores nulos en los datasets analizados.
- Se evidenció desbalance de clases en distintos niveles según el tipo de ataque.
- Las columnas finales sí corresponden a attack_t y attack_a.
- attack_a es binaria.
- Cada archivo contiene tráfico normal (none) + un tipo específico de ataque.